import { jsPDF } from "jspdf";

export function downloadLearningKit(learningData) {
  if (!learningData) return;

  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const margin = 20;
  const maxWidth = pageWidth - margin * 2;

  let y = 25;

  function addTitle(text) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text(text, margin, y);
    y += 14;
  }

  function addHeading(text) {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = 25;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(text, margin, y);
    y += 10;
  }

  function addParagraph(text) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    const lines = doc.splitTextToSize(text, maxWidth);

    lines.forEach((line) => {
      if (y > pageHeight - 20) {
        doc.addPage();
        y = 25;
      }

      doc.text(line, margin, y);
      y += 7;
    });

    y += 8;
  }

  // --------------------------
  // Header
  // --------------------------

  addTitle("LearnTube");
  addParagraph("AI Generated Learning Kit");

  // --------------------------
  // Summary
  // --------------------------

  addHeading("Summary");

  addParagraph(learningData.summary);

  // --------------------------
  // Notes
  // --------------------------

  addHeading("Study Notes");

  learningData.notes.forEach((note, index) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);

    if (y > pageHeight - 30) {
      doc.addPage();
      y = 25;
    }

    doc.text(`${index + 1}. ${note.title}`, margin, y);

    y += 8;

    addParagraph(note.content);
  });

  // --------------------------
  // Footer
  // --------------------------

  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
      "Generated by LearnTube",
      margin,
      pageHeight - 10
    );

    doc.text(
      `Page ${i} of ${pages}`,
      pageWidth - 40,
      pageHeight - 10
    );
  }

  doc.save("LearnTube-Learning-Kit.pdf");
}